# Structure des données *Liste* (classique) de Python

In [2]:
my_list = [1, 2, 3]

In [3]:
my_list

[1, 2, 3]

# Utilisation du module Numpy

In [1]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

La méthode Array() convertit un objet séquentiel (préférablement d'éléments de même type) en un tableau Numpy

In [6]:
tab = np.array(my_list)

In [7]:
tab

array([1, 2, 3])

In [8]:
type(tab)

numpy.ndarray

ndarray : nd (n - dimensional) array

## Liste d'éléments de type différent

In [11]:
liste1 = [1, 2.0, "Justine"]
for item in liste1 :
    print(type(item))

<class 'int'>
<class 'float'>
<class 'str'>


In [15]:
tab1 = np.array(liste1)
tab1

array(['1', '2.0', 'Justine'], dtype='<U32')

Numpy crée un tableau d'éléements de même type en prennant le type le plus général possible (parmi les types d'éléments dans la liste)

In [16]:
tab2 = np.array([1, True, 2.0])
tab2

array([1., 1., 2.])

Ci dessus le type le plus général est le float et "True" (variable binaire) est convertit à 1.0 (False étant 0.0)

# Les Tableaux Bi- dimensionnel (matrices)

In [17]:
liste3 = [[1, 3, 7], [2, 4, 6], [9, 11, 13]]
liste3

[[1, 3, 7], [2, 4, 6], [9, 11, 13]]

In [21]:
matrice = np.array(liste3)
matrice
print(type(liste3))
print(type(matrice))

<class 'list'>
<class 'numpy.ndarray'>


**Remarques** : 

    1. liste3 est une liste python, d'éléments étant également des liste
    
    2. matrice est un objet Numpy (array de 2 dimensions)

    3. pour créer une matrice cohérente, les listes constituant la matrice (en ligne) doivent avoir le même nombre d'élément

    4. La matrice créée est de taille (dimension) n x p où : 
        - n : nombre des lignes (listes)
        - p : nombre des colonnes (nombre d'éléments d'une des listes constituant la matrice)

# Méthode : arange()

In [25]:
tab3 = np.arange(10)
tab3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arange(n) : crée un tableau Numpy uni-dimensionnel d'entiers de 0 à n exclu (de 0 à n-1)

In [26]:
tab4 = np.arange(5, 50, 2.5)
tab4

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5, 30. ,
       32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5])

arange(start, stop, step) : crée un tableau d'éléments allant de **start** à **stop** exclut, avec un pas d'incrémentation de **step**

In [29]:
np.arange(20, 9, -2)

array([20, 18, 16, 14, 12, 10])

marche aussi avec un **pas** négatif **(start > stop)**

# Attribut : shape

In [ ]:
tab = np.array([[1, 3, 5], [2, 4, 6], [7, 9, 11]])
tab
print(tab.shape)

(3, 3)


***shape*** est un attribut de la classe (module) Numpy, il indique la dimension de l'objet

# Méthodes : reshape() et resize()

In [4]:
tab5 = np.arange(12)
tab5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
mat1 = tab5.reshape((3, 4))
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Remarques:**

1. la méthode reshape() est appelée sur un objet du module Numpy (comme en Programmation Orientée Objet)
2. cette méthode prend un seul argument : un tuple (a, b) où a est le nombre des lignes et b, des colonnes
3. il est crucial que le produit a x b soit égale à la taille du vecteur (uni-dimensionnel) de départ (ici tab5)
4. La méthode reshape() crée un nouveau tableau sans modifier l'original
   

In [16]:
tab.resize((2, 3), refcheck = False)
tab

array([[1, 3, 5],
       [2, 4, 6]])

**Remarques :**

1. la méthode resize() est appelée sur un objet Numpy
2. cette méthode prend en argument un tuple et refcheck = False
3. refcheck permet de vérifier toutes les références (utilisations) à l'objet avant de le modifier
4. contrairement à reshape(), la méthode resize() modifie le tableau initial
5. le tuple (a, b) en premier argument n'est pas contraint au produit a x b égale à la taille du tableau initial
6. Si a x b est inférieur au tableau initial alors certains éléments seront supprimés
7. si le produit est supérieur à la dimension du tableau original alors, ce dernier sera complété avec des valeurs par défaut (comme 0 pour un tableau d'éléments entiers)


# Autre méthode resize() : np.resize()

In [20]:
tab = np.arange(6)
mat2 = np.resize(tab, (6,8))
mat2

array([[0, 1, 2, 3, 4, 5, 0, 1],
       [2, 3, 4, 5, 0, 1, 2, 3],
       [4, 5, 0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5, 0, 1],
       [2, 3, 4, 5, 0, 1, 2, 3],
       [4, 5, 0, 1, 2, 3, 4, 5]])

# **Remarques :**

1. Ici l'appelle est faite avec l'alias ***np*** de Numpy
2. en argument, le tableau (vecteur) initial et le tuple (dimension souhaitée)
3. le tableau initial n'est pas modifié (similaire à la méthode reshape() vu précédemmennt)
4. si la dimension souhaitée est plus grande que la taille du vecteur initial alors le remplissage du nouveau tableau sera fait avec des valeurs du tableau initial au risque de répétions


# Construction automatique des tableaux remarquables

## Le vecteur nul et la matrice nulle (float)

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## vecteur et matrice contenant que des 1 (float)

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## On peut avoir des entiers

In [26]:
np.zeros((2, 4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.ones((3,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## la méthode full() : tableau d'éléments identique autre que 0 ou 1

In [28]:
np.full((3,4), 9, int)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

Cette méthode prend en arguments respectivement : un tuple (dimension souhaitée du tableau), ***la valeur*** à remplir dans le tableau et enfin le type (int ou float)

## La matrice identité (1 sur la diagonale et 0 ailleurs)

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

En tant que matrice carrée (nombre des lignes identique à celui des colonnes), **un seul** paramètre suffit

# Méthode diag()

In [30]:
mat = np.arange(1, 17).reshape((4,4))
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

1. Récupérer la diagonale principale (sous forme d'un tableau Numpy)

In [32]:
np.diag(mat)

array([ 1,  6, 11, 16])

2. Récupérer la diagonale supérieure (au dessus de la diagonale principale) : **k = 1**

In [33]:
np.diag(mat, k = 1)

array([ 2,  7, 12])

3. Récupérer la diagonale au dessus de la précédente : **k = 2**

In [34]:
np.diag(mat, k = 2)

array([3, 8])

Ainsi de suite... Les diagonales inférieures ont un fonctionnement similaire, à la précision du paramètre **k** qui est **négatif**

# Construction d'une matrice Diagonale

In [37]:
vecteur = np.array([2, 4, 6, 8])
matrice_diagonale = np.diag(vecteur)
matrice_diagonale

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

Construction d'une matrice diagonale dont les éléments de la diagonale principale sont ceux d'un vecteur Numpy passé en argument

In [38]:
matrice_diagonale_inf = np.diag(vecteur, k = -1)
matrice_diagonale_inf

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 8, 0]])

Le parmètre **k = -1** indique que la diagonale inférieure sera remplie par les éléments du vecteur en paramètre et des 0 ailleurs. Les diagonales supérieurs nécessitent un paramètre **k strictement positif**

# Méthode linspace()

In [39]:
np.linspace(5, 10, 20)

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

np.linspace(debut, fin, n) :  Effectue une subdivision de **n** morceaux de l'intervalle dont **la borne inférieur** est **debut** et **la borne supérieure** est **fin** (les bornes étant atteintes)

# Tableaux aléatoires d'éléments compris entre 0 et 1 (intervale \[0, 1])

In [43]:
np.random.rand(10)

array([0.57868042, 0.24538684, 0.02970301, 0.43036155, 0.10774151,
       0.97006876, 0.5710518 , 0.87425961, 0.75007002, 0.52438461])

méthode rand() du sous module **random** de **Numpy** qui prend en argument le nombre d'éléments à produire du vecteur aléatoire

In [45]:
np.random.rand(3,3)

array([[0.37550533, 0.22381506, 0.48594128],
       [0.34155241, 0.00198359, 0.35104043],
       [0.2090062 , 0.72539901, 0.80840365]])

Pour les matrice aléatoire, deux arguments que sont les nombre des lignes et des colonnes (pas un tuple)

## Valeurs aléatoires issues d'une distribution Gaussienne centrée réduite

In [46]:
np.random.randn(5)

array([ 0.1216381 , -0.2001229 , -0.52259722, -2.57476008,  0.11865978])

Dans le sous module Random du module Numpy, c'est la méthode **randn()**, avec en argument le nombre des valeurs souhaitées pour le vecteur (***deux nombres*** en arguments pour ***le cas d'une matrice***)


In [47]:
np.random.randn(5, 6)

array([[-0.24616869, -0.29862159, -0.86374124,  0.93250439,  0.51550932,
        -0.93530337],
       [-0.59256646, -0.69190976, -0.14150194, -0.67522733,  1.42142499,
        -0.91229087],
       [-0.36647845, -0.71988932,  0.26281499,  0.02923866, -0.50597093,
        -1.23719294],
       [ 2.50544577, -0.6178535 ,  1.07613839, -0.1332717 , -0.47214882,
         0.11816049],
       [-1.61579505, -0.86350726,  1.10798949,  1.71353266,  1.07358869,
        -0.18857852]])

# Tableaux aléatoires d'entiers

## Un nombre aléatoire entre début et fin (exclut)

In [48]:
np.random.randint(0, 100)

10

## Un vecteur aléatoire de 10 élements entre 0 et 100 (exclut)

In [49]:
np.random.randint(0, 100, 10)

array([23, 59, 89,  8, 35, 77, 12, 98, 51, 77])

## Une matrice aléatoire de taille (4, 6) d'élément entre -25 et 315

In [51]:
np.random.randint(-25, 315, (4, 6))

array([[106, 239, 313, 302, 206, 136],
       [109, 208, 235, 214, 213,  -9],
       [267,  42, 280, 280, 122,  72],
       [ 31, 248, 112, 166, 249, 180]])

# Distribution normale aléatoire paramétrée au choix (moyenne et écart-type)

In [7]:
np.random.normal(loc = 10, scale = 2, size = (4, 4))

array([[ 5.34896788, 11.47021359, 11.05012207, 11.63051443],
       [10.08487726, 10.14870484, 12.13966571, 12.48341467],
       [ 8.53560204, 11.27824942, 13.94233152, 11.18778264],
       [13.44382557,  9.60326789, 11.05546172, 10.48787663]])

les arguments : **loc** (moyenne) et **scale** (écart-type); **size** est la dimension de mon tableau (vecteur ou matrice)

# Méthodes de calcul sur les tableaux Numpy

## Le Maximum

In [12]:
tab = np.random.randint(1, 101, 15)
print(tab)
print("la valeur maximale est : ", tab.max())
print("l'indice de la valeur maximale est : ", tab.argmax())

[ 92   6  75  13  39  62  97   9 100  20  24  28  17  72  13]
la valeur maximale est :  100
l'indice de la valeur maximale est :  8


In [18]:
mat = np.random.randint(0, 200, 25).reshape((5,5))
print(mat)
print("le vecteur max de chaque colonne : ", mat.max(axis = 0))

[[175 146   4  58  80]
 [ 32 100  46  66  31]
 [  6  85  31  46  87]
 [ 77 158 110 157  26]
 [ 40 174 112  36 164]]
le vecteur max de chaque colonne :  [175 174 112 157 164]


**axis** est un paramètre qui idinque la dimension selon laquelle chaque élément du vecteur sera trié.
*axis* = **0** : le maximum en considérant les colonnes de la matrice et *axis* = **1**, pour les lignes.

Plusieurs méthodes du module Numpy ont un fonctionnement similaire, notamment : **mean** (moyenne), **sum** (somme), **std** (écart - type), etc...